[project]
name = "sphinx"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# Define all contracts in the `contracts` section
[contracts]
PHI = { path = "contracts/PHI.clar" }
X2410201 = { path = "contracts/X2410201.clar" }
X2410202 = { path = "contracts/X2410202.clar" }
X2410203 = { path = "contracts/X2410203.clar" }
R2410201 = { path = "contracts/R2410201.clar" }
R2410202 = { path = "contracts/R2410202.clar" }
R2410203 = { path = "contracts/R2410203.clar" }

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_contracts = [] }
